### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Xiaojieqiu**

### CODE REVIEW

**Comment by Xiaojieqiu** [comment]
@Sichao25 can you please update the readme file to support clicking the badget for the building of the package?

**Comment by Sichao25** [comment]
> @Sichao25 can you please update the readme file to support clicking the badget for the building of the package?

No problem.

**Review by Sichao25 — COMMENTED** [review]
Done

**Comment by Xiaojieqiu** [comment]
thanks

**Pull request merged**
