### PR TITLE
fix #403

### LINKED ISSUE #403: The animation instance created by mv.StreamFuncAnim does not work properly
- [x] I am sure this issue is not simply a general python programming problem
      (if so, please google the answers).
- [x] I have searched github issues and confirm this issue has not reported previously.
- [x] I have confirmed this bug is not related to dynamo version and it exists on the latest version of dynamo.

---

** If this is a question and not a bug report or enhancement request, please post to our Github Discussions channel at [https://github.com/aristoteleo/dynamo-release/discussions](https://github.com/aristoteleo/dynamo-release/discussions)**

**Describe the bug**
The animation of cell fate prediction cannot be rendered properly. Although the animation instance and animation object could be properly created, when the instance's `update` method get called, an error would raise during clearing previously plotted dots by setting `self.ax.lines = []`. The reason might be that `matplotlib.pyplot.Axes`'s editable `lines` attribute has been deprecated. 

**To Reproduce**
The code that produced the bug:
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax = dyn.pl.topography(rpe1_kinetics, basis='RFP_GFP', color='Cell_cycle_relativePos', ax=ax, save_show_or_return='return', fps_basis='RFP_GFP')
ax.set_aspect(0.8)

instance = dyn.mv.StreamFuncAnim(adata=rpe1_kinetics, basis='RFP_GFP', color='Cell_cycle_relativePos', ax=ax, fig=fig)

import matplotlib
matplotlib.rcParams['animation.embed_limit'] = 2**128 # Ensure all frames will be embedded.

from matplotlib import animation
import numpy as np

anim = animation.FuncAnimation(instance.fig, instance.update, init_func=instance.init_background,
                               frames=np.arange(100), interval=100, blit=True)
from IPython.core.display import display, HTML
HTML(anim.to_jshtml()) # embedding to jupyter notebook.
```

Minimal data may be provided to reproduce the bug
**Traceback**
Post the error message from the Tracebook output:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/ciel/local_documents/py/dynamo/dynamo_tutorial/scrna_seq_3.ipynb Cell 20 in <cell line: 10>()
      [7](vscode-notebook-cell:/Users/ciel/local_documents/py/dynamo/dynamo_tutorial/scrna_seq_3.ipynb#X25sZmlsZQ%3D%3D?line=6) anim = animation.FuncAnimation(instance.fig, instance.update, init_func=instance.init_background,
      [8](vscode-notebook-cell:/Users/ciel/local_documents/py/dynamo/dynamo_tutorial/scrna_seq_3.ipynb#X25sZmlsZQ%3D%3D?line=7)                                frames=np.arange(100), interval=100, blit=True)
      [9](vscode-notebook-cell:/Users/ciel/local_documents/py/dynamo/dynamo_tutorial/scrna_seq_3.ipynb#X25sZmlsZQ%3D%3D?line=8) from IPython.core.display import display, HTML
---> [10](vscode-notebook-cell:/Users/ciel/local_documents/py/dynamo/dynamo_tutorial/scrna_seq_3.ipynb#X25sZmlsZQ%3D%3D?line=9) HTML(anim.to_jshtml())

File /opt/anaconda3/envs/dynamo/lib/python3.10/site-packages/matplotlib/animation.py:1331, in Animation.to_jshtml(self, fps, embed_frames, default_mode)
   1327         path = Path(tmpdir, "temp.html")
   1328         writer = HTMLWriter(fps=fps,
   1329                             embed_frames=embed_frames,
   1330                             default_mode=default_mode)
-> 1331         self.save(str(path), writer=writer)
   1332         self._html_representation = path.read_text()
   1334 return self._html_representation

File /opt/anaconda3/envs/dynamo/lib/python3.10/site-packages/matplotlib/animation.py:1089, in Animation.save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)
   1086 for data in zip(*[a.new_saved_frame_seq() for a in all_anim]):
   1087     for anim, d in zip(all_anim, data):
   1088         # TODO: See if turning off blit is really necessary
-> 1089         anim._draw_next_frame(d, blit=False)
   1090         if progress_callback is not None:
   1091             progress_callback(frame_number, total_frames)

File /opt/anaconda3/envs/dynamo/lib/python3.10/site-packages/matplotlib/animation.py:1124, in Animation._draw_next_frame(self, framedata, blit)
   1120 def _draw_next_frame(self, framedata, blit):
   1121     # Breaks down the drawing of the next frame into steps of pre- and
   1122     # post- draw, as well as the drawing of the frame itself.
   1123     self._pre_draw(framedata, blit)
-> 1124     self._draw_frame(framedata)
   1125     self._post_draw(framedata, blit)

File /opt/anaconda3/envs/dynamo/lib/python3.10/site-packages/matplotlib/animation.py:1718, in FuncAnimation._draw_frame(self, framedata)
   1714 self._save_seq = self._save_seq[-self.save_count:]
   1716 # Call the func with framedata and args. If blitting is desired,
   1717 # func needs to return a sequence of any artists that were modified.
-> 1718 self._drawn_artists = self._func(framedata, *self._args)
   1720 if self._blit:
   1722     err = RuntimeError('The animation function must return a sequence '
   1723                        'of Artist objects.')

File /opt/anaconda3/envs/dynamo/lib/python3.10/site-packages/dynamo/movie/fate.py:223, in StreamFuncAnim.update(self, frame)
    220 if frame == 0:
    221     x, y = init_states.T
--> 223     self.ax.lines = []
    224     (self.ln,) = self.ax.plot(x, y, "ro", zorder=20)
    225     return (self.ln,)  # return line so that blit works properly

AttributeError: can't set attribute 'lines'
```
**Expected behavior**
The `HTML(anim.to_jshtml())` should render and embed a playable animation in Jupyter notebook.  

**Screenshots**

**session_info.show():**
Install session-info via `pip install session-info` and post the output after running session_info.show()

```
import session_info
session_info.show()
-----
session_info        1.0.0
-----
Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ]
macOS-10.16-x86_64-i386-64bit
-----
Session information updated at 2022-08-24 10:07
```

**Additional context**

### PR DESCRIPTION
**Pull request by elfofmaxwell**
fix #403

### CODE REVIEW

**Comment by Xiaojieqiu** [comment]
thanks Honghao! this is a great start, let us add an empty line after your added code

**Comment by Xiaojieqiu** [comment]
should we also update our requirements for matplotlib in requirements.txt and make sure all other plotting functions compatibility with this version of matplotlib?

**Comment by elfofmaxwell** [comment]
The children of Axes including `Axes.lines` are deprecated in matplotlib 3.5.0. I did not find other problems about the rest plotting functions relating with matplotlib, but I believe that updating the requirement list might be useful to prevent unexpected problems when upgrading.

**Comment by Xiaojieqiu** [comment]
great, can you please also help with fixing the following version related issues: 

https://github.com/aristoteleo/dynamo-release/issues/368
https://github.com/aristoteleo/dynamo-release/issues/326
https://github.com/aristoteleo/dynamo-release/issues/323
https://github.com/aristoteleo/dynamo-release/issues/273

Once you fix all these bugs, I will review the code, close the associated issues and merge it to the main branch. 

Thanks

**Pull request merged**
