### PR TITLE
Linting and Formatting automation

### PR DESCRIPTION
**Pull request by AayushSabharwal**
- Separate Flake8 into its own action, since it doesn't need to be run in a matrix of python versions and is independent of tests
- Add `.flake8` config to be in line with black formatting
- Add action to check if code is formatted as per black standards
- Format all code as per black
- Flake8 action fails until all issues are resolved, to make sure that eventually they will be

If the formatting is acceptable, this can be used to ensure all commits/PRs are formatted appropriately. Ensuring the code is all as per flake8 can be done gradually.

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Flake8 errors are now down to ~1850

**Comment by AayushSabharwal** [comment]
Now down to 1491

**Comment by AayushSabharwal** [comment]
Down to 945!

**Comment by AayushSabharwal** [comment]
787 Errors now

**Comment by Ukyeon** [comment]
We have identified 769 remaining errors, but many of them would be resolved by upcoming pull requests that address docstring or formatting issues. Therefore, we will handle these errors later again, once those changes are submitted to the main branch.

**Pull request closed without merging**
